-- DATAKOD adýnda database oluþturunuz.
CREATE DATABASE DATAKOD 
-- Oluþturulan bu database altýnda PERSONEL adýnda bir tablo oluþturunuz.
--PERSONEL tablosu altýnda AD,SOYAD,DOGUMTARÝHÝ adýnda 3 kolon oluþturunuz.
CREATE TABLE PERSONEL (
AD VARCHAR(100),
SOYAD VARCHAR(100),
DOGUMTARÝHÝ DATE
)
SELECT * FROM PERSONEL

--Bu tabloya 10 INSERT iþlemi yapýnýz. 
INSERT INTO PERSONEL(AD,SOYAD,DOGUMTARÝHÝ) VALUES('Sümeyye','Þiþman','1998-05-25')
INSERT INTO PERSONEL(AD,SOYAD,DOGUMTARÝHÝ) VALUES('Nevra','Makarnacý','1999-07-12')
INSERT INTO PERSONEL(AD,SOYAD,DOGUMTARÝHÝ) VALUES('Kaan','Teke','1997-03-02')
INSERT INTO PERSONEL(AD,SOYAD,DOGUMTARÝHÝ) VALUES('Asude','Tan','1999-02-18')
INSERT INTO PERSONEL(AD,SOYAD,DOGUMTARÝHÝ) VALUES('Yiðit','Mucýk','1998-01-16')
INSERT INTO PERSONEL(AD,SOYAD,DOGUMTARÝHÝ) VALUES('Berat','Meþe','1999-08-20')
INSERT INTO PERSONEL(AD,SOYAD,DOGUMTARÝHÝ) VALUES('Sena','Gölcüklü','1998-04-08')
GO 2
UPDATE PERSONEL SET SOYAD='Yýlmaz' WHERE SOYAD='Gölcüklü' 
INSERT INTO PERSONEL(AD,SOYAD,DOGUMTARÝHÝ) VALUES('Yaðmur','Kalaycý','1999-06-23')



